name: Build

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install
      run: pod install
    - name: Build
      run: xcodebuild build-for-testing -workspace ogc-api-features-json-ios.xcworkspace -scheme ogc-api-features-json-ios -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14'
